### ISSUE TITLE
Conda install fails on osx

### ISSUE THREAD

**Issue by thiago-carneiro** [nv-legate/legate.core#106]
> conda install -c nvidia -c conda-forge -c legate legate-core

PackagesNotFoundError: The following packages are not available from current channels:

  - legate-core

Current channels:

  - https://conda.anaconda.org/nvidia/osx-arm64
  - https://conda.anaconda.org/nvidia/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/legate/osx-arm64
  - https://conda.anaconda.org/legate/noarch

**Comment by manopapad** [comment]
For this release we only built conda packages for Linux. We will likely add packages for other platforms in the future, but for now you will need to build from source on MacOS. If you are interested in trying that I am happy to provide assistance (everything should be functional, I build on my local MacOS machine regularly, just note that OpenMP is not supported by the default clang compiler).

**Comment by HarryES95** [comment]
Hi, would you be able to provide a guide for building from source? I have tried install.py however I am receiving a KeyError:
`python install.py --cuda --with-cuda 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA'`

`
Traceback (most recent call last):
  File "setup.py", line 80, in <module>
    exec(code)
  File "install.py", line 941, in <module>
    driver()
  File "install.py", line 937, in driver
    install(unknown=unknown, **vars(args))
  File "install.py", line 551, in install
    pyversion, pylib_name = find_active_python_version_and_path()
  File "install.py", line 104, in find_active_python_version_and_path
    paths = [os.path.join(cv[p], cv["LDLIBRARY"]) for p in ("LIBDIR", "LIBPL")]
  File "install.py", line 104, in <listcomp>
    paths = [os.path.join(cv[p], cv["LDLIBRARY"]) for p in ("LIBDIR", "LIBPL")]
KeyError: 'LIBDIR'
`

Thanks!

**Comment by manopapad** [comment]
@HarryES95 I opened https://github.com/nv-legate/legate.core/issues/127 to address your question
