### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'python' (Python3 is there)

### ISSUE THREAD

**Issue by jeffhammond** [nv-legate/legate.core#15]
I do not use Python2, but I am using Ubuntu 20 and Python3 is `python3`.  I did `alias python=python3` but that didn't help.  I tried with Python2 (as `python`) but that failed too (see second section).

How do I install with Python3?  Thanks.

# Python3
```
Installation complete
Traceback (most recent call last):
  File "./setup.py", line 73, in <module>
    exec(code)
  File "install.py", line 981, in <module>
    driver()
  File "install.py", line 977, in driver
    install(unknown=unknown, **vars(args))
  File "install.py", line 684, in install
    build_legion(
  File "install.py", line 363, in build_legion
    verbose_check_call(
  File "install.py", line 68, in verbose_check_call
    subprocess.check_call(*args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'
```

# Python2
```sh
Installation complete
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/legate
copying legate/__init__.py -> build/lib.linux-x86_64-2.7/legate
creating build/lib.linux-x86_64-2.7/legate/core
copying legate/core/legion.py -> build/lib.linux-x86_64-2.7/legate/core
copying legate/core/legate.py -> build/lib.linux-x86_64-2.7/legate/core
copying legate/core/install_info.py -> build/lib.linux-x86_64-2.7/legate/core
copying legate/core/__init__.py -> build/lib.linux-x86_64-2.7/legate/core
creating build/lib.linux-x86_64-2.7/legate/timing
copying legate/timing/timing.py -> build/lib.linux-x86_64-2.7/legate/timing
copying legate/timing/__init__.py -> build/lib.linux-x86_64-2.7/legate/timing
running install_lib
copying build/lib.linux-x86_64-2.7/legate/core/install_info.py -> /home/jhammond/LEGATE/lib/python2.7/site-packages/legate/core
byte-compiling /home/jhammond/LEGATE/lib/python2.7/site-packages/legate/core/install_info.py to install_info.pyc
byte-compiling /home/jhammond/LEGATE/lib/python2.7/site-packages/legate/timing/timing.py to timing.pyc
  File "/home/jhammond/LEGATE/lib/python2.7/site-packages/legate/timing/timing.py", line 84
    raise ValueError(f"Invalid store count: {len(stores)}")
                                                         ^
SyntaxError: invalid syntax

running install_egg_info
Removing /home/jhammond/LEGATE/lib/python2.7/site-packages/legate.core-0.1-py2.7.egg-info
Writing /home/jhammond/LEGATE/lib/python2.7/site-packages/legate.core-0.1-py2.7.egg-info
```

**Comment by jeffhammond** [comment]
```sh
~/LEGATE/core$ alias python=python3
~/LEGATE/core$ python ./setup.py --install-dir $HOME/LEGATE --cuda --with-cuda /opt/nvidia/hpc_sdk/Linux_x86_64/21.3/cuda/11.2 --arch volta 2>&1 | tee py3.log
```
[py3.log](https://github.com/nv-legate/legate.core/files/6469488/py3.log)

**Comment by manopapad** [comment]
Can you pull and try again?

**Comment by jeffhammond** [comment]
Thanks! That fixes it.
