### ISSUE TITLE
ignored exceptions during region manager destruction

### ISSUE THREAD

**Issue by rohany** [nv-legate/legate.core#407]
I see errors like this during execution of a program (i can provide a reproducer offline).

```
KeyError: <legate.core._legion.region.Region object at 0x7f2e4811ad40>
Exception ignored in: <function Field.__del__ at 0x7f2e5eb3e3b0>
Traceback (most recent call last):
  File "/home/rohany/nvidia/install/lib/python3.10/site-packages/legate/core/store.py", line 93, in __del__
    runtime.free_field(
  File "/home/rohany/nvidia/install/lib/python3.10/site-packages/legate/core/runtime.py", line 1373, in free_field
    self.field_managers[key].free_field(region, field_id)
  File "/home/rohany/nvidia/install/lib/python3.10/site-packages/legate/core/runtime.py", line 346, in free_field
    self.runtime.free_region_manager(
  File "/home/rohany/nvidia/install/lib/python3.10/site-packages/legate/core/runtime.py", line 1309, in free_region_manager
    self.destroy_region_manager(region_mgr, unordered)
  File "/home/rohany/nvidia/install/lib/python3.10/site-packages/legate/core/runtime.py", line 1316, in destroy_region_manager
    del self.region_managers_by_region[region]
KeyError: <legate.core._legion.region.Region object at 0x7f2e364ce620>
```

**Comment by magnatelee** [comment]
@rohany can you pull #418 and see if that fixes this issue?

**Comment by rohany** [comment]
Yes, that fix works for me.
