### ISSUE TITLE
Cmake not copying updated legion.h to install location

### ISSUE THREAD

**Issue by manopapad** [nv-legate/legate.core#463]
Note that the source `legion.h` contains updates, and is more recent than the installed version:

```
(legate) rohany@g0002:~/nvidia/legate.core$ diff legion/runtime/legion.h _skbuild/linux-x86_64-3.8/cmake-install/include/legion.h
3534c3534
<       void finalize(Context ctx, Task* task = NULL) const;
---
>       void finalize(Context ctx) const;
(legate) rohany@g0002:~/nvidia/legate.core$ touch legion/runtime/legion.h
```

When I try to build legate.core with changes that use the new API:

```
diff --git a/src/core/task/return.cc b/src/core/task/return.cc
index 3a9cd92..95bf685 100644
--- a/src/core/task/return.cc
+++ b/src/core/task/return.cc
[snip]
@@ -270,12 +277,22 @@ void ReturnValues::finalize(Context legion_context) const
   if (kind == Processor::TOC_PROC) CHECK_CUDA(cudaDeviceSynchronize());
 #endif

+  // std::cout << "-- many return values" << std::endl; std::cout.flush();
   size_t return_size = legion_buffer_size();
   auto return_buffer =
     UntypedDeferredValue(return_size, find_memory_kind_for_executing_processor());
   AccessorWO<int8_t, 1> acc(return_buffer, return_size, false);
   legion_serialize(acc.ptr(0));
-  return_buffer.finalize(legion_context);
+  // if (context.can_raise_exception() && return_size == 1 && context.scalars().size() == 4) {
+  //   auto unique_id = task->get_unique_id();
+  //   auto shape = context.scalars()[3].value<Legion::DomainPoint>();
+  //   int8_t* ptr = acc.ptr(0);
+  //   std::cout << "unique_id " << unique_id << " task_id " << task->task_id << " for shape " << shape << ": packed single-byte exception buffer with contents: " << (int)(*ptr);
+  //   // std::cout << "PACK: " << return_size << " bytes:";
+  //   // for (int i = 0; i < return_size; ++i) std::cout << " " << (int)(*(ptr + i));
+  //   std::cout << std::endl; std::cout.flush();
+  // }
+  return_buffer.finalize(legion_context, task);
 }

 void register_exception_reduction_op(Runtime* runtime, const LibraryContext& context)
```

I get an error, because the updated `legion.h` is not getting copied over to the install location, so `return.cc` is compiled against the old `legion.h`:

<details>
<summary>Compile output</summary>

```
(legate) rohany@g0002:~/nvidia/legate.core$ LEGION_DIR=../legate.core/legion ../quickstart/build.sh
Command: ./install.py --verbose --editable --legion-src-dir ../legate.core/legion '--march native' --arch pascal --conduit ibv --network gasnet1
Verbose build is  on
networks: ['gasnet1']
cuda: True
arch: pascal
openmp: True
march: native
hdf: False
llvm: False
spy: False
conduit: ibv
nccl_dir: None
cmake_exe: cmake
cmake_generator: Ninja
install_dir: None
gasnet_dir: None
pylib_name: None
cuda_dir: /usr/local/cuda-11.7
maxdim: 4
maxfields: 256
debug: False
debug_release: False
check_bounds: False
clean_first: False
extra_flags: []
editable: True
build_isolation: True
thread_count: None
verbose: True
thrust_dir: None
legion_dir: None
legion_src_dir: ../legate.core/legion
legion_url: https://gitlab.com/StanfordLegion/legion.git
legion_branch: control_replication
Using python lib and version: /home/rohany/anaconda3/envs/legate/lib/libpython3.8.so, 3.8.13
legate_core_dir:  /home/rohany/nvidia/legate.core
cuda_dir:  /usr/local/cuda-11.7
nccl_dir:  None
legion_dir:  None
legion_src_dir:  /home/rohany/nvidia/legate.core/legion
gasnet_dir:  None
thrust_dir:  None
install_dir:  /home/rohany/anaconda3/envs/legate
Executing: " /home/rohany/anaconda3/envs/legate/bin/python3 -m pip install --root / --prefix /home/rohany/anaconda3/envs/legate --no-deps --no-build-isolation --editable . -vv " with  {'cwd': '/home/rohany/nvidia/legate.core', 'env': {'SHELL': '/bin/bash', 'SCRIPT_DIR': '/home/rohany/nvidia/quickstart', 'SLURM_STEP_NUM_TASKS': '1', 'SLURM_JOB_USER': 'rohany', 'SLURM_TASKS_PER_NODE': '1', 'SLURM_JOB_UID': '1036', 'SLURM_CPU_BIND': 'quiet,mask_cpu:0xFFFFFFFFFF', 'SLURM_TASK_PID': '987341', 'CONDA_EXE': '/home/rohany/anaconda3/bin/conda', '_CE_M': '', 'PLATFORM': 'sapling', 'SLURM_LOCALID': '0', 'SLURM_SUBMIT_DIR': '/home/rohany', 'SLURM_CPU_BIND_VERBOSE': 'quiet', 'SLURMD_NODENAME': 'g0002', 'SLURM_STEP_NODELIST': 'g0002', 'MODULES_LMCONFLICT': 'slurm/20.11.4&slurm:mpi/openmpi/4.1.0&mpi:cuda/11.7&cuda', '_LMFILES__modshare': '/usr/local/modules/slurm/20.11.4:1:/usr/local/modules/cuda/11.7:1:/usr/local/modules/mpi/openmpi/4.1.0:1', 'CUDA': '/usr/local/cuda-11.7', 'SLURM_CLUSTER_NAME': 'cluster', 'OMPI_MCA_btl_openib_allow_ib': '1', 'SLURM_CPUS_ON_NODE': '40', 'SLURM_UMASK': '0002', 'SLURM_JOB_CPUS_PER_NODE': '40', 'MANPATH_modshare': '/usr/local/share/man:1:/usr/local/man:1:/usr/share/man:1:/usr/local/modules-3.2.10/share/man:1:/usr/local/slurm-20.11.4/share/man:2', 'ENV': '/usr/share/modules/init/profile.sh', 'PWD': '/home/rohany/nvidia/legate.core', 'USE_OPENMP': '1', 'SLURM_GTIDS': '0', 'LOGNAME': 'rohany', 'CONDA_PREFIX': '/home/rohany/anaconda3/envs/legate', 'SLURM_JOB_PARTITION': 'gpu', 'MODULESHOME': '/usr/share/modules', 'MANPATH': '/usr/local/man:/usr/local/share/man:/usr/share/man:/usr/local/modules-3.2.10/share/man:/usr/local/slurm-20.11.4/share/man', 'SLURM_JOB_NUM_NODES': '1', 'CXX': 'mpicxx', 'SRUN_DEBUG': '3', 'SLURM_STEPID': '0', 'SLURM_CPU_BIND_LIST': '0xFFFFFFFFFF', 'SLURM_JOBID': '16251', 'SLURM_PTY_PORT': '42547', 'SLURM_LAUNCH_NODE_IPADDR': '10.1.0.254', 'USE_CUDA': '1', 'HOME': '/home/rohany', 'SLURM_PTY_WIN_ROW': '80', 'LANG': 'en_US.UTF-8', 'SLURM_CPU_BIND_TYPE': 'mask_cpu:', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'LD_LIBRARY_PATH_modshare': '/usr/local/openmpi-4.1.0/lib:2:/usr/local/cuda-11.7/lib64:1', 'SLURM_PROCID': '0', 'NETWORK': 'gasnet1', 'CONDA_PROMPT_MODIFIER': '(legate) ', 'TMPDIR': '/tmp', 'LC_TERMINAL': 'iTerm2', 'SLURM_NTASKS': '1', 'SLURM_TOPOLOGY_ADDR': 'g0002', 'SSH_CONNECTION': '216.228.112.22 48907 171.67.76.18 22', 'PATH_modshare': '/usr/bin:1:/usr/local/cuda-11.7/bin:1:/usr/local/bin:1:/home/rohany/anaconda3/bin:1:/usr/local/openmpi-4.1.0/bin:2:/bin:1:/sbin:1:/home/rohany/anaconda3/condabin:1:/usr/sbin:1:/usr/games:1:/usr/local/sbin:1:/usr/local/slurm-20.11.4/bin:2:/usr/local/games:1', 'GASNET_EXTRA_CONFIGURE_ARGS': ' --enable-ibv-multirail --with-ibv-max-hcas=1', 'SLURM_TOPOLOGY_ADDR_PATTERN': 'node', 'SLURM_SRUN_COMM_HOST': '10.1.0.254', 'NUM_NICS': '1', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'MODULEPATH_modshare': '/etc/environment-modules/modules:1:/usr/share/modules/$MODULE_VERSION/modulefiles:1:/usr/local/modules:1:/usr/share/modules/versions:1:/usr/share/modules/modulefiles:1', 'XDG_SESSION_COOKIE': 'b4977195c392e5c8dbc73196599124c7-1667252083.366482-655172018', 'LOADEDMODULES_modshare': 'mpi/openmpi/4.1.0:1:slurm/20.11.4:1:cuda/11.7:1', 'SLURM_WORKING_CLUSTER': 'cluster:sapling:6817:9216:109', 'TERM': 'xterm-256color', '_CE_CONDA': '', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'SLURM_PTY_WIN_COL': '253', 'GPU_ARCH': 'pascal', 'USER': 'rohany', 'SLURM_NODELIST': 'g0002', 'MPI_ROOT': '/usr/local/openmpi-4.1.0', 'CONDA_SHLVL': '2', 'LEGION_DIR': '../legate.core/legion', 'SLURM_SRUN_COMM_PORT': '34454', 'LOADEDMODULES': 'slurm/20.11.4:mpi/openmpi/4.1.0:cuda/11.7', 'LC_TERMINAL_VERSION': '3.4.16', 'SLURM_STEP_ID': '0', 'MODULES_LMCONFLICT_modshare': 'mpi/openmpi/4.1.0&mpi:1:cuda/11.7&cuda:1:slurm/20.11.4&slurm:1', 'SLURM_PRIO_PROCESS': '0', 'MARCH_ARG': "'--march native'", 'SLURM_NPROCS': '1', 'SHLVL': '3', 'SLURM_NNODES': '1', 'BASH_ENV': '/usr/share/modules/init/bash', 'XDG_SESSION_ID': '2804', 'SLURM_SUBMIT_HOST': 'sapling', 'CONDA_PYTHON_EXE': '/home/rohany/anaconda3/bin/python', 'LD_LIBRARY_PATH': '/usr/local/openmpi-4.1.0/lib:/usr/local/cuda-11.7/lib64', 'CONDUIT': 'ibv', 'XDG_RUNTIME_DIR': '/run/user/1036', 'SLURM_JOB_ID': '16251', 'SLURM_NODEID': '0', 'SLURM_STEP_NUM_NODES': '1', 'SSH_CLIENT': '216.228.112.22 48907 22', 'CONDA_DEFAULT_ENV': 'legate', 'SLURM_STEP_TASKS_PER_NODE': '1', 'SLURM_CONF': '/etc/slurm.conf', 'PATH': '/home/rohany/anaconda3/envs/legate/bin:/home/rohany/anaconda3/condabin:/usr/local/openmpi-4.1.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/slurm-20.11.4/bin:/usr/local/cuda-11.7/bin', 'SLURM_JOB_NAME': 'bash', 'MODULEPATH': '/etc/environment-modules/modules:/usr/share/modules/versions:/usr/share/modules/$MODULE_VERSION/modulefiles:/usr/share/modules/modulefiles:/usr/local/modules', 'CC': 'mpicc', '_LMFILES_': '/usr/local/modules/slurm/20.11.4:/usr/local/modules/mpi/openmpi/4.1.0:/usr/local/modules/cuda/11.7', 'MAIL': '/var/mail/rohany', 'SSH_TTY': '/dev/pts/85', 'CONDA_PREFIX_1': '/home/rohany/anaconda3', 'SLURM_STEP_LAUNCHER_PORT': '34454', 'SLURM_JOB_GID': '1036', 'OLDPWD': '/home/rohany/nvidia/legate.sparse', 'SLURM_JOB_NODELIST': 'g0002', 'MODULES_CMD': '/usr/lib/x86_64-linux-gnu/modulecmd.tcl', 'BASH_FUNC_switchml%%': '() {  typeset swfound=1;\n if [ "${MODULES_USE_COMPAT_VERSION:-0}" = \'1\' ]; then\n typeset swname=\'main\';\n if [ -e /usr/lib/x86_64-linux-gnu/modulecmd.tcl ]; then\n typeset swfound=0;\n unset MODULES_USE_COMPAT_VERSION;\n fi;\n else\n typeset swname=\'compatibility\';\n if [ -e /usr/lib/x86_64-linux-gnu/modulecmd-compat ]; then\n typeset swfound=0;\n MODULES_USE_COMPAT_VERSION=1;\n export MODULES_USE_COMPAT_VERSION;\n fi;\n fi;\n if [ $swfound -eq 0 ]; then\n echo "Switching to Modules $swname version";\n source /usr/share/modules/init/bash;\n else\n echo "Cannot switch to Modules $swname version, command not found";\n return 1;\n fi\n}', 'BASH_FUNC_module%%': '() {  _module_raw "$@" 2>&1\n}', 'BASH_FUNC__module_raw%%': '() {  unset _mlshdbg;\n if [ "${MODULES_SILENT_SHELL_DEBUG:-0}" = \'1\' ]; then\n case "$-" in \n *v*x*)\n set +vx;\n _mlshdbg=\'vx\'\n ;;\n *v*)\n set +v;\n _mlshdbg=\'v\'\n ;;\n *x*)\n set +x;\n _mlshdbg=\'x\'\n ;;\n *)\n _mlshdbg=\'\'\n ;;\n esac;\n fi;\n unset _mlre _mlIFS;\n if [ -n "${IFS+x}" ]; then\n _mlIFS=$IFS;\n fi;\n IFS=\' \';\n for _mlv in ${MODULES_RUN_QUARANTINE:-};\n do\n if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" -a "${_mlv}" = "${_mlv#[0-9]}" ]; then\n if [ -n "`eval \'echo ${\'$_mlv\'+x}\'`" ]; then\n _mlre="${_mlre:-}${_mlv}_modquar=\'`eval \'echo ${\'$_mlv\'}\'`\' ";\n fi;\n _mlrv="MODULES_RUNENV_${_mlv}";\n _mlre="${_mlre:-}${_mlv}=\'`eval \'echo ${\'$_mlrv\':-}\'`\' ";\n fi;\n done;\n if [ -n "${_mlre:-}" ]; then\n eval `eval ${_mlre}/usr/bin/tclsh8.6 /usr/lib/x86_64-linux-gnu/modulecmd.tcl bash \'"$@"\'`;\n else\n eval `/usr/bin/tclsh8.6 /usr/lib/x86_64-linux-gnu/modulecmd.tcl bash "$@"`;\n fi;\n _mlstatus=$?;\n if [ -n "${_mlIFS+x}" ]; then\n IFS=$_mlIFS;\n else\n unset IFS;\n fi;\n unset _mlre _mlv _mlrv _mlIFS;\n if [ -n "${_mlshdbg:-}" ]; then\n set -$_mlshdbg;\n fi;\n unset _mlshdbg;\n return $_mlstatus\n}', '_': './install.py', 'SETUPTOOLS_ENABLE_FEATURES': 'legacy-editable', 'SKBUILD_BUILD_OPTIONS': '-j40', 'SKBUILD_CONFIGURE_OPTIONS': '-GNinja\n--log-level=VERBOSE\n-DCMAKE_BUILD_TYPE=Release\n-DBUILD_SHARED_LIBS=ON\n-DBUILD_MARCH=native\n-DCMAKE_CUDA_ARCHITECTURES=pascal\n-DLegion_MAX_DIM=4\n-DLegion_MAX_FIELDS=256\n-DLegion_SPY=OFF\n-DLegion_BOUNDS_CHECKS=OFF\n-DLegion_USE_CUDA=ON\n-DLegion_USE_OpenMP=ON\n-DLegion_USE_LLVM=OFF\n-DLegion_NETWORKS=gasnet1\n-DLegion_USE_HDF5=OFF\n-DLegion_USE_Python=ON\n-DLegion_Python_Version=3.8.13\n-DLegion_REDOP_COMPLEX=ON\n-DLegion_REDOP_HALF=ON\n-DLegion_BUILD_BINDINGS=ON\n-DLegion_BUILD_JUPYTER=ON\n-DGASNet_CONDUIT=ibv\n-DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-11.7\n-DCPM_Legion_SOURCE=/home/rohany/nvidia/legate.core/legion\n-Dlegate_core_LEGION_REPOSITORY=https://gitlab.com/StanfordLegion/legion.git\n-Dlegate_core_LEGION_BRANCH=control_replication'}}
Using pip 22.2.2 from /home/rohany/anaconda3/envs/legate/lib/python3.8/site-packages/pip (python 3.8)
Non-user install due to --prefix or --target option
Created temporary directory: /tmp/pip-ephem-wheel-cache-kpguuzlu
Created temporary directory: /tmp/pip-build-tracker-i84_ie8d
Initialized build tracking at /tmp/pip-build-tracker-i84_ie8d
Created build tracker: /tmp/pip-build-tracker-i84_ie8d
Entered build tracker: /tmp/pip-build-tracker-i84_ie8d
Created temporary directory: /tmp/pip-install-4xn_udav
Obtaining file:///home/rohany/nvidia/legate.core
  Added file:///home/rohany/nvidia/legate.core to build tracker '/tmp/pip-build-tracker-i84_ie8d'
  Running command Checking if build backend supports build_editable
  Checking if build backend supports build_editable ... done
  Created temporary directory: /tmp/pip-modern-metadata-m08xal7e
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating /tmp/pip-modern-metadata-m08xal7e/legate.core.egg-info
  writing /tmp/pip-modern-metadata-m08xal7e/legate.core.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-modern-metadata-m08xal7e/legate.core.egg-info/dependency_links.txt
  writing entry points to /tmp/pip-modern-metadata-m08xal7e/legate.core.egg-info/entry_points.txt
  writing requirements to /tmp/pip-modern-metadata-m08xal7e/legate.core.egg-info/requires.txt
  writing top-level names to /tmp/pip-modern-metadata-m08xal7e/legate.core.egg-info/top_level.txt
  writing manifest file '/tmp/pip-modern-metadata-m08xal7e/legate.core.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-modern-metadata-m08xal7e/legate.core.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-modern-metadata-m08xal7e/legate.core.egg-info/SOURCES.txt'
  creating '/tmp/pip-modern-metadata-m08xal7e/legate.core-22.10.0.dev0+101.gb4d7669.dirty.dist-info'
  adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
  /home/rohany/anaconda3/envs/legate/lib/python3.8/site-packages/setuptools/dist.py:530: UserWarning: Normalizing '22.10.00.dev+101.gb4d7669.dirty' to '22.10.0.dev0+101.gb4d7669.dirty'
    warnings.warn(tmpl.format(**locals()))
  Preparing metadata (pyproject.toml) ... done
  Source in /home/rohany/nvidia/legate.core has version 22.10.0.dev0+101.gb4d7669.dirty, which satisfies requirement legate.core==22.10.0.dev0+101.gb4d7669.dirty from file:///home/rohany/nvidia/legate.core
  Removed legate.core==22.10.0.dev0+101.gb4d7669.dirty from file:///home/rohany/nvidia/legate.core from build tracker '/tmp/pip-build-tracker-i84_ie8d'
Created temporary directory: /tmp/pip-unpack-4353fq35
Installing collected packages: legate.core
  Running setup.py develop for legate.core
    Running command python setup.py develop
    [1/5] touch build.ninja so ninja doesn't re-run CMake on rebuild
    [2/5] touch build.ninja so ninja doesn't re-run CMake on rebuild
    [3/5] Building CXX object /home/rohany/nvidia/legate.core/build/CMakeFiles/legate_core.dir/src/core/task/return.cc.o
    FAILED: /home/rohany/nvidia/legate.core/build/CMakeFiles/legate_core.dir/src/core/task/return.cc.o
    /usr/local/openmpi-4.1.0/bin/mpicxx -DLEGATE_USE_CUDA -DLEGATE_USE_NETWORK -DLEGATE_USE_OPENMP -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP -DUSE_CUDA -Dlegate_core_EXPORTS -I/home/rohany/nvidia/legate.core/src -I/home/rohany/nvidia/legate.core/_skbuild/linux-x86_64-3.8/cmake-build/_deps/thrust-src -I/home/rohany/nvidia/legate.core/_skbuild/linux-x86_64-3.8/cmake-build/_deps/thrust-src/dependencies/cub -isystem /home/rohany/anaconda3/envs/legate/include -isystem /usr/local/cuda-11.7/include -isystem /home/rohany/nvidia/legate.core/_skbuild/linux-x86_64-3.8/cmake-install/include -isystem /home/rohany/nvidia/legate.core/_skbuild/linux-x86_64-3.8/cmake-install/include/mappers -O2 -fPIC -march=native -UTHRUST_DEVICE_SYSTEM -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_OMP -std=gnu++17 -MD -MT /home/rohany/nvidia/legate.core/build/CMakeFiles/legate_core.dir/src/core/task/return.cc.o -MF /home/rohany/nvidia/legate.core/build/CMakeFiles/legate_core.dir/src/core/task/return.cc.o.d -o /home/rohany/nvidia/legate.core/build/CMakeFiles/legate_core.dir/src/core/task/return.cc.o -c /home/rohany/nvidia/legate.core/src/core/task/return.cc
    /home/rohany/nvidia/legate.core/src/core/task/return.cc: In member function ‘void legate::ReturnValues::finalize(const Legion::Task*, Legion::Runtime*, Legion::Context, legate::TaskContext&) const’:
    /home/rohany/nvidia/legate.core/src/core/task/return.cc:295:46: error: no matching function for call to ‘Legion::UntypedDeferredValue::finalize(Legion::Internal::TaskContext*&, const Legion::Task*&)’
      295 |   return_buffer.finalize(legion_context, task);
          |                                              ^
    In file included from /home/rohany/nvidia/legate.core/src/core/task/return.cc:21:
    /home/rohany/nvidia/legate.core/_skbuild/linux-x86_64-3.8/cmake-install/include/legion.h:3534:12: note: candidate: ‘void Legion::UntypedDeferredValue::finalize(Legion::Context) const’
     3534 |       void finalize(Context ctx) const;
          |            ^~~~~~~~
    /home/rohany/nvidia/legate.core/_skbuild/linux-x86_64-3.8/cmake-install/include/legion.h:3534:12: note:   candidate expects 1 argument, 2 provided
    ninja: build stopped: subcommand failed.
    /home/rohany/anaconda3/envs/legate/lib/python3.8/site-packages/setuptools/dist.py:530: UserWarning: Normalizing '22.10.00.dev+101.gb4d7669.dirty' to '22.10.0.dev0+101.gb4d7669.dirty'
      warnings.warn(tmpl.format(**locals()))
    /home/rohany/anaconda3/envs/legate/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
      File "/home/rohany/anaconda3/envs/legate/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
        cmkr.make(make_args, install_target=cmake_install_target, env=env)
      File "/home/rohany/anaconda3/envs/legate/lib/python3.8/site-packages/skbuild/cmaker.py", line 680, in make
        self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
      File "/home/rohany/anaconda3/envs/legate/lib/python3.8/site-packages/skbuild/cmaker.py", line 704, in make_impl
        raise SKBuildError(
    An error occurred while building with CMake.
      Command:
        cmake --build . --target install --config Release -- -j40
      Install target:
        install
      Source directory:
        /home/rohany/nvidia/legate.core
      Working directory:
        /home/rohany/nvidia/legate.core/_skbuild/linux-x86_64-3.8/cmake-build
    Please check the install target is valid and see CMake's output for more information.
    Traceback (most recent call last):

    error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /home/rohany/anaconda3/envs/legate/bin/python3 -c '
    exec(compile('"'"''"'"''"'"'
    # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
    #
    # - It imports setuptools before invoking setup.py, to enable projects that directly
    #   import from `distutils.core` to work with newer packaging standards.
    # - It provides a clear error message when setuptools is not installed.
    # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
    #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
    #     manifest_maker: standard file '"'"'-c'"'"' not found".
    # - It generates a shim setup.py, for handling setup.cfg-only projects.
    import os, sys, tokenize

    try:
        import setuptools
    except ImportError as error:
        print(
            "ERROR: Can not execute `setup.py` since setuptools is not available in "
            "the build environment.",
            file=sys.stderr,
        )
        sys.exit(1)

    __file__ = %r
    sys.argv[0] = __file__

    if os.path.exists(__file__):
        filename = __file__
        with tokenize.open(__file__) as f:
            setup_py_code = f.read()
    else:
        filename = "<auto-generated setuptools caller>"
        setup_py_code = "from setuptools import setup; setup()"

    exec(compile(setup_py_code, filename, "exec"))
    '"'"''"'"''"'"' % ('"'"'/home/rohany/nvidia/legate.core/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' develop --no-deps --prefix /home/rohany/anaconda3/envs/legate
    cwd: /home/rohany/nvidia/legate.core/
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Exception information:
Traceback (most recent call last):
  File "/home/rohany/anaconda3/envs/legate/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/rohany/anaconda3/envs/legate/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/home/rohany/anaconda3/envs/legate/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 461, in run
    installed = install_given_reqs(
  File "/home/rohany/anaconda3/envs/legate/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "/home/rohany/anaconda3/envs/legate/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 763, in install
    install_editable_legacy(
  File "/home/rohany/anaconda3/envs/legate/lib/python3.8/site-packages/pip/_internal/operations/install/editable_legacy.py", line 43, in install_editable
    call_subprocess(
  File "/home/rohany/anaconda3/envs/legate/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
    raise error
pip._internal.exceptions.InstallationSubprocessError: python setup.py develop exited with 1
Remote version of pip: 22.3
Local version of pip:  22.2.2
Was pip installed by pip? False
Removed build tracker: '/tmp/pip-build-tracker-i84_ie8d'
Traceback (most recent call last):
  File "./install.py", line 770, in <module>
    driver()
  File "./install.py", line 766, in driver
    install(unknown=unknown, **vars(args))
  File "./install.py", line 473, in install
    execute_command(pip_install_cmd, verbose, cwd=legate_core_dir, env=cmd_env)
  File "./install.py", line 75, in execute_command
    subprocess.check_call(args, **kwargs)
  File "/home/rohany/anaconda3/envs/legate/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/rohany/anaconda3/envs/legate/bin/python3', '-m', 'pip', 'install', '--root', '/', '--prefix', '/home/rohany/anaconda3/envs/legate', '--no-deps', '--no-build-isolation', '--editable', '.', '-vv']' returned non-zero exit status 1.
```

</details>

**Comment by trxcllnt** [comment]
I believe this should be fixed by https://github.com/nv-legate/legate.core/pull/455
