### ISSUE TITLE
Installing Legate.Core __habs undefined (Legion Runtime) 

### ISSUE THREAD

**Issue by kwaters4** [nv-legate/legate.core#48]
# Problem 
I am compiling the Legate.core and I am getting the following error inside of the legion/runtime directory. 

```
/home/cosmicbox/Documents/legate.core/legion/runtime/mathtypes/half.h(364): error: identifier "__habs" is undefined

1 error detected in the compilation of "/tmp/tmpxft_0000417d_00000000-6_legion_redop.cpp1.ii".
make: *** [/home/cosmicbox/Documents/legate.core/legion/runtime/runtime.mk:1333: /home/cosmicbox/Documents/legate.core/legion/runtime/legion/legion_redop.cu.o] Error 1

```

# Steps to reproduce
```
./install.py --cuda --with-cuda /usr/local/cuda-10.1 --python-lib /usr/local/lib/libpython3.7m.a
```

# Versions
```
OS = CENTOS8
CUDA = 10.1 
g++ = 8.4.1 
PYTHON = 3.7.11
PyArrow = 1.0.1
```

I was able to clone and run tests from the legion runtime. 
I am unsure where to go next to tackle this undefined function. 
Any help is appreciated. Just let me know if I should post this with the legion runtime folks.

**Comment by manopapad** [comment]
It looks like the host compiler invoked by `nvcc` is not finding function `__habs` from `cuda_fp16.h`. Could you please run the install script again from the same directory, using the following command line, and share the output?

```
NVCC_FLAGS=-v ./install.py --cuda --with-cuda /usr/local/cuda-10.1 -j 1 --noclean --verbose
```

Unrelated, but AFAIU `--python-lib` takes a dynamic, not a static library (this file is eventually `dlopen`-ed by Realm), and should only be necessary if you want to compile Legate against a different python version than the one used to run the `./install.py` script (I'll update the documentation to reflect this).

**Comment by kwaters4** [comment]
Thanks for the suggestion about the dynamic library, I have a new install and forgot to install a developer version so the .so file did not exist. I changed to Python 3.9.2 and reproduced the error.

Turing should be compatible with the Volta architecture?

# Command 
NVCC_FLAGS=-v ./install.py --cuda --with-cuda /usr/local/cuda-10.1 -j 1 --noclean --verbose

# Output 
```
Using python lib and version: /usr/lib64/libpython3.9.so, 3.9.2
Executing: " make LG_RT_DIR=/home/cosmicbox/Documents/legate.core/legion/runtime DEBUG=0 DEBUG_RELEASE=0 MAX_DIM=4 MAX_FIELDS=256 USE_CUDA=1 GPU_ARCH=volta USE_OPENMP=1 USE_LLVM=0 USE_GASNET=0 USE_HDF=0 PREFIX=/home/cosmicbox PYTHON_VERSION_MAJOR=3 PYTHON_VERSION_MINOR=9 PYTHON_LIB=/usr/lib64/libpython3.9.so FORCE_PYTHON=1 USE_COMPLEX=1 USE_HALF=1 USE_SPY=0 REALM_USE_CUDART_HIJACK=0 CUDA=/usr/local/cuda-10.1 -j 1 install " with  {'cwd': '/home/cosmicbox/Documents/legate.core/legion/bindings/python'}
Version string from git: legion-21.06.0-2965-g3141d7c06
/usr/bin/python /home/cosmicbox/Documents/legate.core/legion/runtime/../tools/generate_defines.py  -DLEGION_VERSION='"legion-21.06.0-2965-g3141d7c06"' -DLEGION_REDOP_HALF -DLEGION_REDOP_COMPLEX -DLEGION_USE_LIBDL -DLEGION_USE_CUDA -DLEGION_USE_ZLIB -DLEGION_MAX_DIM=4 -DLEGION_MAX_FIELDS=256 -c -i /home/cosmicbox/Documents/legate.core/legion/runtime/../cmake/legion_defines.h.in -o /home/cosmicbox/Documents/legate.core/legion/bindings/python/legion_defines.h
/usr/bin/python /home/cosmicbox/Documents/legate.core/legion/runtime/../tools/generate_defines.py  -DREALM_VERSION='"legion-21.06.0-2965-g3141d7c06"' -DREALM_LIMIT_SYMBOL_VISIBILITY -DREALM_USE_LIBDL -DREALM_USE_OPENMP -DREALM_OPENMP_GOMP_SUPPORT -DREALM_OPENMP_KMP_SUPPORT -DREALM_PYTHON_LIB="\"/usr/lib64/libpython3.9.so\"" -DREALM_PYTHON_VERSION_MAJOR=3 -DREALM_USE_PYTHON -DREALM_USE_CUDA -DREALM_MAX_DIM=4 -DCOMPILE_TIME_MIN_LEVEL=LEVEL_DEBUG  -c -i /home/cosmicbox/Documents/legate.core/legion/runtime/../cmake/realm_defines.h.in -o /home/cosmicbox/Documents/legate.core/legion/bindings/python/realm_defines.h
/usr/local/cuda-10.1/bin/nvcc -o /home/cosmicbox/Documents/legate.core/legion/runtime/legion/legion_redop.cu.o -c /home/cosmicbox/Documents/legate.core/legion/runtime/legion/legion_redop.cu -v -ccbin g++ -Xcompiler -fPIC -O2 -I/home/cosmicbox/Documents/legate.core/install/thrust  -DVOLTA_ARCH -gencode arch=compute_70,code=sm_70 -Xcudafe --diag_suppress=boolean_controlling_expr_is_constant  -I/home/cosmicbox/Documents/legate.core/legion/bindings/python -I/home/cosmicbox/Documents/legate.core/legion/runtime -I/home/cosmicbox/Documents/legate.core/legion/runtime/mappers -I/usr/local/cuda-10.1/include
#$ _SPACE_=
#$ _CUDART_=cudart
#$ _HERE_=/usr/local/cuda-10.1/bin
#$ _THERE_=/usr/local/cuda-10.1/bin
#$ _TARGET_SIZE_=
#$ _TARGET_DIR_=
#$ _TARGET_DIR_=targets/x86_64-linux
#$ TOP=/usr/local/cuda-10.1/bin/..
#$ NVVMIR_LIBRARY_DIR=/usr/local/cuda-10.1/bin/../nvvm/libdevice
#$ LD_LIBRARY_PATH=/usr/local/cuda-10.1/bin/../lib:/usr/local/cuda-10.1/lib64:/usr/local/cuda-10.1/lib64:/usr/local/lib/python37.zip:/usr/local/lib/python3.7:/usr/local/lib/python3.7/lib-dynload:/home/cosmicbox/.local/lib/python3.7/site-packages:/usr/local/lib/python3.7/site-packages:/usr/local/lib/python37.zip:/usr/local/lib/python3.7:/usr/local/lib/python3.7/lib-dynload:/home/cosmicbox/.local/lib/python3.7/site-packages:/usr/local/lib/python3.7/site-packages
#$ PATH=/usr/local/cuda-10.1/bin/../nvvm/bin:/usr/local/cuda-10.1/bin:/usr/local/cuda-10.1/bin:/home/cosmicbox/.local/bin:/home/cosmicbox/bin:/usr/local/cuda-10.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
#$ INCLUDES="-I/usr/local/cuda-10.1/bin/../targets/x86_64-linux/include"
#$ LIBRARIES=  "-L/usr/local/cuda-10.1/bin/../targets/x86_64-linux/lib/stubs" "-L/usr/local/cuda-10.1/bin/../targets/x86_64-linux/lib"
#$ CUDAFE_FLAGS=
#$ PTXAS_FLAGS=
#$ g++ -D__CUDA_ARCH__=700 -E -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__  -fPIC -O2 -I"/home/cosmicbox/Documents/legate.core/install/thrust" -I"/home/cosmicbox/Documents/legate.core/legion/bindings/python" -I"/home/cosmicbox/Documents/legate.core/legion/runtime" -I"/home/cosmicbox/Documents/legate.core/legion/runtime/mappers" -I"/usr/local/cuda-10.1/include" "-I/usr/local/cuda-10.1/bin/../targets/x86_64-linux/include"    -D "VOLTA_ARCH" -D__CUDACC_VER_MAJOR__=10 -D__CUDACC_VER_MINOR__=1 -D__CUDACC_VER_BUILD__=243 -include "cuda_runtime.h" -m64 "/home/cosmicbox/Documents/legate.core/legion/runtime/legion/legion_redop.cu" > "/tmp/tmpxft_00001a0c_00000000-6_legion_redop.cpp1.ii"
#$ cicc --c++14 --gnu_version=80401 --allow_managed  --diag_suppress=boolean_controlling_expr_is_constant  -arch compute_70 -m64 -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name "tmpxft_00001a0c_00000000-2_legion_redop.fatbin.c" -tused -nvvmir-library "/usr/local/cuda-10.1/bin/../nvvm/libdevice/libdevice.10.bc" --gen_module_id_file --module_id_file_name "/tmp/tmpxft_00001a0c_00000000-3_legion_redop.module_id" --orig_src_file_name "/home/cosmicbox/Documents/legate.core/legion/runtime/legion/legion_redop.cu" --gen_c_file_name "/tmp/tmpxft_00001a0c_00000000-5_legion_redop.cudafe1.c" --stub_file_name "/tmp/tmpxft_00001a0c_00000000-5_legion_redop.cudafe1.stub.c" --gen_device_file_name "/tmp/tmpxft_00001a0c_00000000-5_legion_redop.cudafe1.gpu"  "/tmp/tmpxft_00001a0c_00000000-6_legion_redop.cpp1.ii" -o "/tmp/tmpxft_00001a0c_00000000-5_legion_redop.ptx"
/home/cosmicbox/Documents/legate.core/legion/runtime/mathtypes/half.h(364): error: identifier "__habs" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00001a0c_00000000-6_legion_redop.cpp1.ii".
# --error 0x1 --
make: *** [/home/cosmicbox/Documents/legate.core/legion/runtime/runtime.mk:1333: /home/cosmicbox/Documents/legate.core/legion/runtime/legion/legion_redop.cu.o] Error 1
Traceback (most recent call last):
  File "/home/cosmicbox/Documents/legate.core/./install.py", line 935, in <module>
    driver()
  File "/home/cosmicbox/Documents/legate.core/./install.py", line 931, in driver
    install(unknown=unknown, **vars(args))
  File "/home/cosmicbox/Documents/legate.core/./install.py", line 650, in install
    build_legion(
  File "/home/cosmicbox/Documents/legate.core/./install.py", line 376, in build_legion
    verbose_check_call(
  File "/home/cosmicbox/Documents/legate.core/./install.py", line 85, in verbose_check_call
    subprocess.check_call(*args, **kwargs)
  File "/usr/lib64/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'LG_RT_DIR=/home/cosmicbox/Documents/legate.core/legion/runtime', 'DEBUG=0', 'DEBUG_RELEASE=0', 'MAX_DIM=4', 'MAX_FIELDS=256', 'USE_CUDA=1', 'GPU_ARCH=volta', 'USE_OPENMP=1', 'USE_LLVM=0', 'USE_GASNET=0', 'USE_HDF=0', 'PREFIX=/home/cosmicbox', 'PYTHON_VERSION_MAJOR=3', 'PYTHON_VERSION_MINOR=9', 'PYTHON_LIB=/usr/lib64/libpython3.9.so', 'FORCE_PYTHON=1', 'USE_COMPLEX=1', 'USE_HALF=1', 'USE_SPY=0', 'REALM_USE_CUDART_HIJACK=0', 'CUDA=/usr/local/cuda-10.1', '-j', '1', 'install']' returned non-zero exit status 2.
```

**Comment by manopapad** [comment]
I don't see an obvious issue on your output. Could you give us some more info on your CUDA installation? Specifically, please provide the output of `nvidia-smi` on your system, and confirm that you can find the following header file: `/usr/local/cuda-10.1/include/cuda_fp16.h`.

Also, please try to build the Legion python interpreter manually, to verify this isn't something specific to the legate.core install script:

```
git clone https://github.com/StanfordLegion/legion.git
cd legion/bindings/python
make LG_RT_DIR=../../runtime USE_CUDA=1 GPU_ARCH=volta USE_OPENMP=1 PYTHON_VERSION_MAJOR=3 PYTHON_VERSION_MINOR=9 PYTHON_LIB=/usr/lib64/libpython3.9.so FORCE_PYTHON=1 USE_COMPLEX=1 USE_HALF=1 CUDA=/usr/local/cuda-10.1
```

**Comment by kwaters4** [comment]
# Issue 
I was able to solve the issue __habs issue, thanks! It was a case of user error, mismatched CUDA.
```nvidia-smi``` produced 11.4.

I installed ```CUDA 11.4``` to match the output from ```nvidia-smi``` and compiled legate.core against it.

I was able to build legate.core and the legion python interpreter with the command you provided, with the path to cuda 11.4. 

I can open separate issues for the following if that makes documentation easier. Just let me know.

# CFFI
Then I had to install cffi 
```pip install cffi```
# OS Variables 
The import of legate.core prompted an error "LEGATE_MAX_DIM" (noted below), I have not been able to find any reference to the variable outside of your job file or inside the script below. 
``` http://sapling.stanford.edu/~manolis/hijack/without/out.txt```

Same for LEGATE_MAX_FIELDS

Am I missing any documentation on these values? Should they be intuitive?

I can open a separate issue if that makes documentation easier.
```
>>> import legate.core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cosmicbox/Documents/legate.core/legate/core/__init__.py", line 19, in <module>
    from legate.core.context import ResourceConfig
  File "/home/cosmicbox/Documents/legate.core/legate/core/context.py", line 18, in <module>
    from .legion import Future, legion
  File "/home/cosmicbox/Documents/legate.core/legate/core/legion.py", line 29, in <module>
    assert "LEGATE_MAX_DIM" in os.environ
AssertionError
>>> exit()
```
# legion_auto_generate_id
After I defined both values on bash I ran into the following AttributeError:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cosmicbox/Documents/legate.core/legate/core/__init__.py", line 19, in <module>
    from legate.core.context import ResourceConfig
  File "/home/cosmicbox/Documents/legate.core/legate/core/context.py", line 18, in <module>
    from .legion import Future, legion
  File "/home/cosmicbox/Documents/legate.core/legate/core/legion.py", line 915, in <module>
    class IndexPartition(object):
  File "/home/cosmicbox/Documents/legate.core/legate/core/legion.py", line 925, in IndexPartition
    part_id=legion.legion_auto_generate_id(),
  File "/home/cosmicbox/.local/lib/python3.9/site-packages/cffi/api.py", line 912, in __getattr__
    make_accessor(name)
  File "/home/cosmicbox/.local/lib/python3.9/site-packages/cffi/api.py", line 908, in make_accessor
    accessors[name](name)
  File "/home/cosmicbox/.local/lib/python3.9/site-packages/cffi/api.py", line 838, in accessor_function
    value = backendlib.load_function(BType, name)
AttributeError: function/symbol 'legion_auto_generate_id' not found in library '<None>': python3.9: undefined symbol: legion_auto_generate_id
```

Thanks again!

**Comment by manopapad** [comment]
> Then I had to install cffi

Thanks for catching that, it looks like cffi was missing from the dependencies list, I added it.

> The import of legate.core prompted an error "LEGATE_MAX_DIM"

Please run your python program using `<legate-install-dir>/bin/legate`. This script will set up the required environment variables and start Legion before executing your program.

**Comment by kwaters4** [comment]
Perfect. Sorry about missing some of the documentation! 

Thanks.

**Comment by manopapad** [comment]
Sounds good, thanks for trying out Legate!
