### ISSUE TITLE
spurious error messages on shutdown

### ISSUE THREAD

**Issue by rohany** [nv-legate/legate.core#512]
I have an application that prints lots of messages like this on shutdown:

```
Exception ignored in: <function RegionField.__del__ at 0x203236ae5790>
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/rohany/nvidia/legate.core/legate/core/store.py", line 126, in __del__
    self.detach_external_allocation(unordered=True, defer=True)
  File "/autofs/nccs-svm1_home1/rohany/nvidia/legate.core/legate/core/store.py", line 251, in detach_external_allocation
    attachment_manager.detach_external_allocation(
  File "/autofs/nccs-svm1_home1/rohany/nvidia/legate.core/legate/core/runtime.py", line 585, in detach_external_allocation
    self._remove_allocation(alloc)
  File "/autofs/nccs-svm1_home1/rohany/nvidia/legate.core/legate/core/runtime.py", line 570, in _remove_allocation
    self._remove_attachment(alloc)
  File "/autofs/nccs-svm1_home1/rohany/nvidia/legate.core/legate/core/runtime.py", line 565, in _remove_attachment
    raise RuntimeError("Unable to find attachment to remove")
RuntimeError: Unable to find attachment to remove
```.

**Comment by manopapad** [comment]
Is this on a successful exit? We've seen this happen on failed executions, but it would always go away once we fixed the crash.

**Comment by rohany** [comment]
Yes, it's on a successful exit.

**Comment by manopapad** [comment]
OK, can I get a reproducer?
